import JSZip from "jszip";
import { saveAs } from "file-saver";
import type { CodeFile } from "@/types/project";

interface ExportOptions {
  projectName: string;
  files: CodeFile[];
  format: "nextjs" | "react" | "html";
}

export async function exportProject(options: ExportOptions): Promise<void> {
  const { projectName, files, format } = options;
  const zip = new JSZip();

  switch (format) {
    case "nextjs":
      await createNextJsProject(zip, projectName, files);
      break;
    case "react":
      await createReactProject(zip, projectName, files);
      break;
    case "html":
      await createHtmlProject(zip, projectName, files);
      break;
  }

  const content = await zip.generateAsync({ type: "blob" });
  const filename = `${projectName.toLowerCase().replace(/\s+/g, "-")}.zip`;
  saveAs(content, filename);
}

async function createNextJsProject(
  zip: JSZip,
  projectName: string,
  files: CodeFile[]
): Promise<void> {
  // package.json
  zip.file(
    "package.json",
    JSON.stringify(
      {
        name: projectName.toLowerCase().replace(/\s+/g, "-"),
        version: "0.1.0",
        private: true,
        scripts: {
          dev: "next dev",
          build: "next build",
          start: "next start",
          lint: "next lint",
        },
        dependencies: {
          next: "^14.0.0",
          react: "^18.2.0",
          "react-dom": "^18.2.0",
        },
        devDependencies: {
          "@types/node": "^20",
          "@types/react": "^18",
          "@types/react-dom": "^18",
          tailwindcss: "^3.4.0",
          typescript: "^5",
        },
      },
      null,
      2
    )
  );

  // tsconfig.json
  zip.file(
    "tsconfig.json",
    JSON.stringify(
      {
        compilerOptions: {
          target: "es5",
          lib: ["dom", "dom.iterable", "esnext"],
          allowJs: true,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: "esnext",
          moduleResolution: "bundler",
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: "preserve",
          incremental: true,
          paths: {
            "@/*": ["./src/*"],
          },
        },
        include: ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
        exclude: ["node_modules"],
      },
      null,
      2
    )
  );

  // next.config.js
  zip.file(
    "next.config.js",
    `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
};

module.exports = nextConfig;`
  );

  // tailwind.config.js
  zip.file(
    "tailwind.config.js",
    `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};`
  );

  // postcss.config.js
  zip.file(
    "postcss.config.js",
    `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};`
  );

  // Create src directory
  const src = zip.folder("src");
  const app = src?.folder("app");

  // layout.tsx
  app?.file(
    "layout.tsx",
    `import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: '${projectName}',
  description: 'Generated by AI Web Builder',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="zh-CN">
      <body>{children}</body>
    </html>
  );
}`
  );

  // globals.css
  app?.file(
    "globals.css",
    `@tailwind base;
@tailwind components;
@tailwind utilities;`
  );

  // Add project files
  for (const file of files) {
    const fileName = file.name.replace(/\.(tsx|jsx|ts|js)$/, "");
    if (fileName.toLowerCase() === "app") {
      app?.file("page.tsx", file.content);
    } else {
      src?.file(file.name, file.content);
    }
  }

  // README.md
  zip.file(
    "README.md",
    `# ${projectName}

这是一个由 AI Web Builder 生成的 Next.js 项目。

## 开始使用

\`\`\`bash
npm install
npm run dev
\`\`\`

在浏览器中打开 [http://localhost:3000](http://localhost:3000) 查看结果。

## 了解更多

- [Next.js 文档](https://nextjs.org/docs)
- [React 文档](https://reactjs.org/docs)
`
  );

  // .gitignore
  zip.file(
    ".gitignore",
    `# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# local env files
.env*.local

# vercel
.vercel

# typescript
*.tsbuildinfo
next-env.d.ts
`
  );
}

async function createReactProject(
  zip: JSZip,
  projectName: string,
  files: CodeFile[]
): Promise<void> {
  // package.json
  zip.file(
    "package.json",
    JSON.stringify(
      {
        name: projectName.toLowerCase().replace(/\s+/g, "-"),
        version: "0.1.0",
        private: true,
        dependencies: {
          react: "^18.2.0",
          "react-dom": "^18.2.0",
          "react-scripts": "5.0.1",
        },
        devDependencies: {
          "@types/react": "^18",
          "@types/react-dom": "^18",
          tailwindcss: "^3.4.0",
          typescript: "^5",
        },
        scripts: {
          start: "react-scripts start",
          build: "react-scripts build",
          test: "react-scripts test",
          eject: "react-scripts eject",
        },
      },
      null,
      2
    )
  );

  // public/index.html
  const pub = zip.folder("public");
  pub?.file(
    "index.html",
    `<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${projectName}</title>
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>`
  );

  // src folder
  const src = zip.folder("src");

  // index.tsx
  src?.file(
    "index.tsx",
    `import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';

const root = ReactDOM.createRoot(
  document.getElementById('root') as HTMLElement
);
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);`
  );

  // Add project files
  for (const file of files) {
    if (file.name.endsWith(".css")) {
      src?.file("index.css", file.content);
    } else {
      src?.file(file.name, file.content);
    }
  }

  // README.md
  zip.file(
    "README.md",
    `# ${projectName}

这是一个由 AI Web Builder 生成的 React 项目。

## 开始使用

\`\`\`bash
npm install
npm start
\`\`\`

在浏览器中打开 [http://localhost:3000](http://localhost:3000) 查看结果。
`
  );
}

async function createHtmlProject(
  zip: JSZip,
  projectName: string,
  files: CodeFile[]
): Promise<void> {
  // Find main component
  const mainFile = files.find(
    (f) => f.name === "App.tsx" || f.name === "index.tsx"
  );
  const cssFile = files.find((f) => f.name.endsWith(".css"));

  // Create a simple HTML file with embedded React
  zip.file(
    "index.html",
    `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${projectName}</title>
  <script src="https://unpkg.com/react@18/umd/react.production.min.js"></script>
  <script src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js"></script>
  <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
  <script src="https://cdn.tailwindcss.com"></script>
  <style>
    ${cssFile?.content || "body { margin: 0; font-family: system-ui, sans-serif; }"}
  </style>
</head>
<body>
  <div id="root"></div>
  <script type="text/babel">
    ${mainFile?.content || ""}
    const root = ReactDOM.createRoot(document.getElementById('root'));
    root.render(<App />);
  </script>
</body>
</html>`
  );

  // Add source files
  const src = zip.folder("src");
  for (const file of files) {
    src?.file(file.name, file.content);
  }

  // README.md
  zip.file(
    "README.md",
    `# ${projectName}

这是一个由 AI Web Builder 生成的 HTML 项目。

## 使用方法

直接在浏览器中打开 \`index.html\` 文件即可查看。
`
  );
}